language: bash
dist: xenial

before_script:
  - sudo apt-get install -y dos2unix

script:
  - dos2unix bootstrap.sh
  - bash bootstrap.sh
  - sudo service index stop
  - node ./experiment-control/nodejs_websocket/index.js &
  - python ./experiment-control/main.py --action=reserve